# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Guoliang Kang
tagline:          'PhD in Computer Vision and Machine Learning'
description:      'I am currently a postdoctoral research associate at Carnegie Mellon University. I achieved my Ph.D. from Unviersity of Technology Sydney, Australia, supervised by Prof. Yi Yang.'

author:
  name:           'Guoliang Kang'
  email:          'kgl.prml AT gmail.com'
  github:         'https://github.com/kgl-prml'
  scholar:        'https://scholar.google.com.au/citations?user=P24HCsgAAAAJ&hl=en'

paginate:         5

# Custom vars
version:          2.1.0
